version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: my-hackernews-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

volumes:
  postgres_data:


networks:
  postgres_network:
    driver: bridge
