# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: sushen
# "service" is the name of this project. This will also be added to your AWS resource names.
service: myhackernews

custom:
  wsgi:
    app: run.app

provider:
  name: aws
  runtime: python3.12
  region: ap-southeast-1
  memorySize: 256

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

package:
  exclude:
    - .venv/**
    - node_modules/**
    - __pycache__/**

# TODO - setup postgres rds instance

plugins:
  - serverless-wsgi
  - serverless-python-requirements
